In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./output.csv')

In [3]:
df

,location_indicator,SUBJECT,MEASURE,FREQUENCY,TIME,TIME.1,Value,Flag Codes
0,AUS_CPIFORECAST,TOT,AGRWTH,A,2015.0,2015.0,1.508367,NaN
1,AUS_CPIFORECAST,TOT,AGRWTH,A,2016.0,2016.0,1.253773,NaN
2,AUS_CPIFORECAST,TOT,NaN,A,2017.0,2017.0,1.972025,NaN
3,AUS_CPIFORECAST,TOT,AGRWTH,A,2018.0,2018.0,1.933888,NaN
4,AUS_CPIFORECAST,TOT,AGRWTH,A,2019.0,2019.0,1.551138,NaN
...,...,...,...,...,...,...,...,...
324,EA17_CPIFORECAST,TOT,AGRWTH,A,2017.0,2017.0,1.528207,NaN
325,EA17_CPIFORECAST,TOT,AGRWTH,A,2018.0,2018.0,1.761302,NaN
326,EA17_CPIFORECAST,TOT,AGRWTH,A,2019.0,2019.0,1.168102,NaN
327,EA17_CPIFORECAST,TOT,AGRWTH,A,2020.0,2020.0,1.118827,NaN
328,EA17_CPIFORECAST,TOT,AGRWTH,A,2021.0,2021.0,1.378801,NaN

In [12]:
df.to_csv("./DP_LIVE_17032020113916392.csv")    #保存在当前文件夹